"""
api/main.py

The REST API for the Enterprise AI Research & Knowledge Discovery
Platform (Ezitech Case Study AI-003).

Run from the project root:
    uvicorn api.main:app --reload

Then open http://127.0.0.1:8000/docs for interactive API documentation
(auto-generated by FastAPI from the schemas in api/schemas.py).
"""

from contextlib import asynccontextmanager
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from neo4j import GraphDatabase
try:
    import redis
except ImportError:  # pragma: no cover - supports reduced dependency installs
    redis = None

from api.config import settings
from api.schemas import ErrorResponse
from api.routers import health, search, qa, agents, copilot, graph, logs, evidence
from db import postgres

try:
    from agents.copilot import build_graph as _build_graph
except Exception:  # pragma: no cover - optional dependency guard
    def _build_graph():
        raise RuntimeError("Copilot dependencies are unavailable")

build_graph = _build_graph


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initialize optional services without crashing app startup when they are unavailable."""
    app.state.neo4j_driver = None
    app.state.copilot_app = None
    app.state.redis_client = None
    app.state.startup_errors = []

    try:
        app.state.neo4j_driver = GraphDatabase.driver(
            settings.neo4j_uri,
            auth=(settings.neo4j_username, settings.neo4j_password),
        )
        with app.state.neo4j_driver.session() as session:
            session.run("RETURN 1")
    except Exception as exc:
        app.state.startup_errors.append(f"neo4j: {exc}")

    try:
        from agents.copilot import build_graph

        app.state.copilot_app = build_graph()
    except Exception as exc:
        app.state.startup_errors.append(f"copilot: {exc}")

    try:
        postgres.init_pool(settings.postgres_url)
    except Exception as exc:
        app.state.startup_errors.append(f"postgres: {exc}")

    if redis is None:
        app.state.startup_errors.append("redis: Redis package is not installed")
    else:
        try:
            redis_client = redis.Redis.from_url(getattr(settings, "redis_url", "redis://localhost:6379/0"), decode_responses=True)
            redis_client.ping()
            app.state.redis_client = redis_client
        except Exception as exc:
            app.state.startup_errors.append(f"redis: {exc}")

    yield

    try:
        if app.state.neo4j_driver is not None:
            app.state.neo4j_driver.close()
    except Exception:
        pass

    try:
        postgres.close_pool()
    except Exception:
        pass

    try:
        if app.state.redis_client is not None:
            app.state.redis_client.close()
    except Exception:
        pass


app = FastAPI(
    title=settings.api_title,
    version=settings.api_version,
    description=settings.api_description,
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_allow_origins,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    """
    Catches any exception that isn't already handled by a route's own
    try/except, so the API always returns a clean, consistent JSON error
    instead of leaking a raw stack trace to the caller.
    """
    return JSONResponse(
        status_code=500,
        content=ErrorResponse(error="Internal server error", detail=str(exc)).model_dump(),
    )


# Every router is mounted here. Each one owns a focused slice of the API
# surface (search, qa, agents, copilot, graph) rather than one giant
# file of endpoints.
app.include_router(health.router)
app.include_router(search.router)
app.include_router(qa.router)
app.include_router(agents.router)
app.include_router(copilot.router)
app.include_router(graph.router)
app.include_router(logs.router)
app.include_router(evidence.router)


@app.get("/", include_in_schema=False)
def root():
    return {"message": f"{settings.api_title} — see /docs for API documentation"}
